version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    command: flask run --host=0.0.0.0 --port=5005
    networks:
      - db_network
      - web_network
    volumes:
      - ./apps:/apps
      - ./apps/static/assets/images:/apps/static/assets/images
      - ./migrations:/migrations
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
      
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app
  
  db:
      image: postgres:14
      container_name: db
      networks:
        - web_network
      environment:
        - POSTGRES_USER=fastapi
        - POSTGRES_PASSWORD=fastapi123
        - POSTGRES_DB=fastapi_db
      # se quiser persistir dados localmente, pode mapear um volume:
      volumes:
        - ./data/postgres:/var/lib/postgresql/data
      expose:
        - "5432"  # se quiser expor pra host, acrescente "5432:5432" em "ports:"
      ports:
        - "5432:5432"
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
