"""empty message

Revision ID: fd2b618da199
Revises: 
Create Date: 2026-01-22 17:41:50.234693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2b618da199'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.Column('perfil', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('documentos_oficiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('obsoleto', sa.Boolean(), nullable=True),
    sa.Column('sugerido_obsoleto', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ultima_verificacao', sa.DateTime(), nullable=True),
    sa.Column('ultimo_status_http', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thoughts', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_versoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('versao_numero', sa.Integer(), nullable=False),
    sa.Column('url_arquivo', sa.String(length=500), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=128), nullable=True),
    sa.Column('status_processamento', sa.String(length=32), nullable=True),
    sa.Column('chroma_document_id', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('processado_em', sa.DateTime(), nullable=True),
    sa.Column('indexado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_oficiais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chroma_index_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=False),
    sa.Column('chroma_document_id', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['versao_id'], ['documento_versoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_processamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao_id', sa.Integer(), nullable=True),
    sa.Column('agente', sa.String(length=64), nullable=True),
    sa.Column('acao', sa.String(length=64), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('documento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_oficiais.id'], ),
    sa.ForeignKeyConstraint(['versao_id'], ['documento_versoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_processamento')
    op.drop_table('chroma_index_records')
    op.drop_table('documento_versoes')
    op.drop_table('chat_messages')
    op.drop_table('documentos_oficiais')
    op.drop_table('Users')
    # ### end Alembic commands ###
